export const stackIcons = [
    "typescript",
    "javascript",
    "vite",
    "vuedotjs",
    "dotnet",
    "flutter",
    "dart",
    "postgresql",
    "docker",
    "git",
    "github",
    "gitlab",
    "tailwindcss",
    "java",
];
